// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eCommerce.Persistence.Data;

#nullable disable

namespace eCommerce.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts", "purchase");
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems", "purchase");
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasDiscount")
                        .HasColumnType("bit");

                    b.Property<int>("OrderState")
                        .HasColumnType("int");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", "purchase");
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", "purchase");
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentMethods", "billing");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.PaymentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PaymentMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentRecords", "billing");
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", "inventory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fb7a7720-c40a-4eef-bb5e-9a592b6e00c5"),
                            CategoryId = new Guid("28978b4b-df88-4c5a-b371-d4c10eaebff9"),
                            CreatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wireless over-ear headphones with adaptive ANC and 35-hour battery life.",
                            IsDeleted = false,
                            Name = "Auralux Noise Cancelling Headphones",
                            QuantityInStock = 42,
                            UnitPrice = 249.99m,
                            UpdatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("db6f5fd4-bf4e-44b9-88b9-6df6cfd0a13e"),
                            CategoryId = new Guid("28978b4b-df88-4c5a-b371-d4c10eaebff9"),
                            CreatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Low-profile mechanical keyboard with hot-swappable switches and white backlight.",
                            IsDeleted = false,
                            Name = "Pulse Mechanical Keyboard",
                            QuantityInStock = 68,
                            UnitPrice = 129.50m,
                            UpdatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bc7f9c55-ad74-448f-870b-13b8b82f501c"),
                            CategoryId = new Guid("c6f81854-315d-4676-a221-7b578d9d0f44"),
                            CreatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mesh ergonomic chair with adjustable lumbar support and 4D armrests.",
                            IsDeleted = false,
                            Name = "Contour Ergonomic Chair",
                            QuantityInStock = 15,
                            UnitPrice = 389.00m,
                            UpdatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7593a8b6-c0ae-4b0b-b350-37deaf436fc2"),
                            CategoryId = new Guid("c6f81854-315d-4676-a221-7b578d9d0f44"),
                            CreatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Electric standing desk with programmable height presets and cable tray.",
                            IsDeleted = false,
                            Name = "Rise Standing Desk",
                            QuantityInStock = 12,
                            UnitPrice = 599.99m,
                            UpdatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6ea52fd5-f353-42d0-af5e-e09a7997fa8a"),
                            CategoryId = new Guid("4b4fa4f4-6905-4036-808f-c5876c469bb1"),
                            CreatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fitness smartwatch with GPS, sleep tracking, and heart-rate alerts.",
                            IsDeleted = false,
                            Name = "Stride Pro Smart Watch",
                            QuantityInStock = 34,
                            UnitPrice = 199.00m,
                            UpdatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2dd712d1-7cee-4b47-987a-446eb1907f6a"),
                            CategoryId = new Guid("4b4fa4f4-6905-4036-808f-c5876c469bb1"),
                            CreatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Non-slip extra-thick yoga mat designed for home workouts and studio use.",
                            IsDeleted = false,
                            Name = "Balance Grip Yoga Mat",
                            QuantityInStock = 77,
                            UnitPrice = 39.95m,
                            UpdatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories", "inventory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("28978b4b-df88-4c5a-b371-d4c10eaebff9"),
                            Description = "Connected devices and premium personal tech.",
                            IsDeleted = false,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("c6f81854-315d-4676-a221-7b578d9d0f44"),
                            Description = "Desk setups and accessories built for all-day comfort.",
                            IsDeleted = false,
                            Name = "Home Office"
                        },
                        new
                        {
                            Id = new Guid("4b4fa4f4-6905-4036-808f-c5876c469bb1"),
                            Description = "Workout essentials and recovery-focused gear.",
                            IsDeleted = false,
                            Name = "Fitness"
                        });
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.ProductReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Stars")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductReviews", "review");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99a30d2c-9cfb-42cb-8ea0-edc0d5cb3af8"),
                            Comment = "Excellent noise isolation for commuting and the battery easily lasts a full work week.",
                            CreatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("fb7a7720-c40a-4eef-bb5e-9a592b6e00c5"),
                            Stars = 5,
                            UpdatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("8ad8a683-a2c1-4df2-94af-b1b4470cb6d1")
                        },
                        new
                        {
                            Id = new Guid("eb674a0a-cf6a-4d3a-991c-fc95fbc0f944"),
                            Comment = "Comfortable fit and clean sound profile, though the carry case is bulkier than expected.",
                            CreatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("fb7a7720-c40a-4eef-bb5e-9a592b6e00c5"),
                            Stars = 4,
                            UpdatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("bcbd8034-46f1-4e07-9f45-4b3871572a4b")
                        },
                        new
                        {
                            Id = new Guid("08b76ca9-3af4-4dfd-b6d7-4cd7993eef40"),
                            Comment = "Tactile without being too loud. It feels premium and works well for both coding and writing.",
                            CreatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("db6f5fd4-bf4e-44b9-88b9-6df6cfd0a13e"),
                            Stars = 5,
                            UpdatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("8ad8a683-a2c1-4df2-94af-b1b4470cb6d1")
                        },
                        new
                        {
                            Id = new Guid("cf013e87-4588-4230-aad2-6ed6920221da"),
                            Comment = "Assembly took a bit of time, but the lumbar support made a noticeable difference after a few days.",
                            CreatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("bc7f9c55-ad74-448f-870b-13b8b82f501c"),
                            Stars = 4,
                            UpdatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("bcbd8034-46f1-4e07-9f45-4b3871572a4b")
                        },
                        new
                        {
                            Id = new Guid("82eb6ca2-e910-4f2c-ab2d-504c5b71501e"),
                            Comment = "Accurate activity tracking and a bright display. The companion app could be a little faster.",
                            CreatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("6ea52fd5-f353-42d0-af5e-e09a7997fa8a"),
                            Stars = 4,
                            UpdatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("8ad8a683-a2c1-4df2-94af-b1b4470cb6d1")
                        },
                        new
                        {
                            Id = new Guid("01112e2f-7d32-4cb5-92b4-e0b5244620fe"),
                            Comment = "Great grip on hardwood floors and enough padding for longer mobility sessions.",
                            CreatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ProductId = new Guid("2dd712d1-7cee-4b47-987a-446eb1907f6a"),
                            Stars = 5,
                            UpdatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("bcbd8034-46f1-4e07-9f45-4b3871572a4b")
                        });
                });

            modelBuilder.Entity("eCommerce.Domain.Identity.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Accounts", "account");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("eCommerce.Domain.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.CardPaymentMethod", b =>
                {
                    b.HasBaseType("eCommerce.Domain.Entities.PaymentMethod");

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("CardExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.ToTable("CardPaymentMethods", "billing");
                });

            modelBuilder.Entity("eCommerce.Domain.Identity.Admin", b =>
                {
                    b.HasBaseType("eCommerce.Domain.Identity.Account");

                    b.Property<bool>("IsActivated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.ToTable("Admins", "account");
                });

            modelBuilder.Entity("eCommerce.Domain.Identity.SuperAdmin", b =>
                {
                    b.HasBaseType("eCommerce.Domain.Identity.Account");

                    b.ToTable("SuperAdmins", "account");
                });

            modelBuilder.Entity("eCommerce.Domain.Identity.User", b =>
                {
                    b.HasBaseType("eCommerce.Domain.Identity.Account");

                    b.Property<bool>("IsVipUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.ToTable("Users", "account");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ad8a683-a2c1-4df2-94af-b1b4470cb6d1"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1E5EB718-66E6-4596-9091-0D76EF394295",
                            CreatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lena.carter@example.com",
                            EmailConfirmed = true,
                            FullName = "Lena Carter",
                            LockoutEnabled = false,
                            NormalizedEmail = "LENA.CARTER@EXAMPLE.COM",
                            NormalizedUserName = "LENA.CARTER",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            SecurityStamp = "B24E9502-B337-45E0-AF6D-5F1133AE0B0A",
                            TwoFactorEnabled = false,
                            UserName = "lena.carter",
                            IsVipUser = true,
                            Points = 240
                        },
                        new
                        {
                            Id = new Guid("bcbd8034-46f1-4e07-9f45-4b3871572a4b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5403C123-50E6-4292-A88F-774830F1B330",
                            CreatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "marcus.reed@example.com",
                            EmailConfirmed = true,
                            FullName = "Marcus Reed",
                            LockoutEnabled = false,
                            NormalizedEmail = "MARCUS.REED@EXAMPLE.COM",
                            NormalizedUserName = "MARCUS.REED",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            SecurityStamp = "42D1AB89-0A11-4A80-A784-0343D5C5DE4B",
                            TwoFactorEnabled = false,
                            UserName = "marcus.reed",
                            IsVipUser = false,
                            Points = 95
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("eCommerce.Domain.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("eCommerce.Domain.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("eCommerce.Domain.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("eCommerce.Domain.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Domain.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("eCommerce.Domain.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.Cart", b =>
                {
                    b.HasOne("eCommerce.Domain.Identity.User", null)
                        .WithOne("Cart")
                        .HasForeignKey("eCommerce.Domain.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("eCommerce.Domain.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eCommerce.Domain.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.Order", b =>
                {
                    b.HasOne("eCommerce.Domain.Identity.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("eCommerce.Domain.Entities.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.PaymentMethod", b =>
                {
                    b.HasOne("eCommerce.Domain.Identity.User", null)
                        .WithMany("PaymentMethods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.PaymentRecord", b =>
                {
                    b.HasOne("eCommerce.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("eCommerce.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("eCommerce.Domain.Identity.User", null)
                        .WithMany("PaymentRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.Product", b =>
                {
                    b.HasOne("eCommerce.Domain.Entities.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.ProductReview", b =>
                {
                    b.HasOne("eCommerce.Domain.Entities.Product", "Product")
                        .WithMany("ProductReviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Domain.Identity.User", null)
                        .WithMany("ProductReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.CardPaymentMethod", b =>
                {
                    b.HasOne("eCommerce.Domain.Entities.PaymentMethod", null)
                        .WithOne()
                        .HasForeignKey("eCommerce.Domain.Entities.CardPaymentMethod", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eCommerce.Domain.Identity.Admin", b =>
                {
                    b.HasOne("eCommerce.Domain.Identity.Account", null)
                        .WithOne()
                        .HasForeignKey("eCommerce.Domain.Identity.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eCommerce.Domain.Identity.SuperAdmin", b =>
                {
                    b.HasOne("eCommerce.Domain.Identity.Account", null)
                        .WithOne()
                        .HasForeignKey("eCommerce.Domain.Identity.SuperAdmin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eCommerce.Domain.Identity.User", b =>
                {
                    b.HasOne("eCommerce.Domain.Identity.Account", null)
                        .WithOne()
                        .HasForeignKey("eCommerce.Domain.Identity.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductReviews");
                });

            modelBuilder.Entity("eCommerce.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("eCommerce.Domain.Identity.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("PaymentMethods");

                    b.Navigation("PaymentRecords");

                    b.Navigation("ProductReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
