# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deployment Workflow

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]
    types:
      - opened
      - closed
      - edited      


jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Get Code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        cache: true
        cache-dependency-path: "**/packages.lock.json"
    - name: Restore dependencies
      run: dotnet restore ./eCommerceSolution.slnx
    - name: Build
      run: dotnet build ./eCommerceSolution.slnx -c Release --no-restore
    - name: Test
      run: dotnet test ./eCommerceSolution.slnx --no-build --verbosity normal


  build-publish:
    needs: build-test
    runs-on: ubuntu-latest
    outputs: 
      random-number: ${{ steps.publish.outputs.random-num }}
    steps:
    - name: Get Code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        cache: true
        cache-dependency-path: "**/packages.lock.json"        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build for publish
      id: publish
      run: |
        dotnet publish ./src/eCommerce.Api -c Release -o ./publish
        echo "random-num=10" >> "$GITHUB_OUTPUT"
    - name: Uploading Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: publish-artifacts
        path: ./publish

  deploy:
    needs: build-publish
    runs-on: ubuntu-latest

    steps:
      - name: Downloading build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: publish-artifacts
          path: ./publish

      - name: Reading Random Number from build job
        run: echo "${{ needs.build-publish.outputs.random-number }}"
      - name: Deploy
        run: echo "Deploying project ..."
